### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by kjetilmjos** [linkedin/iris#281]
Hi, I'm trying to trigger an incident using the API. But I can't figure out how to get the API key. Is it created automatically with the creation of an application or how does it work? Was also unable to create a new application from UI. Is this something that has to be done via the config file?

**Comment by dwang159** [comment]
API keys are created automatically when an application is created. You can make an application by logging in as an admin user and clicking the "Create application" button in the "Applications" tab. This should take you to a page where the API key is visible.

**Comment by kjetilmjos** [comment]
Thanks that worked! How is the user management for Iris done?

**Comment by wleese** [comment]
```
server:                                                                                                                                                    
    host: 0.0.0.0                                                                                                                                            
    port: 16649                                                                                                                                              
    disable_auth: True
```
With this config you should be able to login with any user.

If disable_auth: False, then you can configure oncall to manage users. Here's an example of LDAP config for *oncall*:

```
  user_sync:                                                                                                                                                 
    module: 'oncall.user_sync.ldap_sync'                                                                                                                     
  ldap_sync:                                                                                                                                                 
    url: 'ldaps://my-ldap-server'                                                                                                                    
    base: 'dc=company,dc=net'                                                                                                                                 
    user: 'cn=binduser,ou=services,dc=company,dc=net'                                                                                                             
    password: 'xxxxx'                                                                                                                         
    cert_path: '/etc/ldap_cert.pem'                                                                                                                          
    query: '(uid=*)'                                                                                                                                    
    attrs:                                                                                                                                                   
      username: 'uid'                                                                                                                                        
      full_name: 'cn'                                                                                                                                        
      mail: 'mail'                                                                                                                                           
      mobile: 'mobile'                                                                                                                                       
    image_url: 'https://image.example.com/api/%s/picture'
```
Then you can run something like:
```
/home/oncall/env/bin/oncall-user-sync /home/oncall/config/config.yaml
/home/iris/env/bin/iris-sync-targets /home/iris/config/config.yaml
```
Which will import the users from ldap into iris. Haven't tried doing anything with users local to iris yet.

* Disclaimer: I'm probably missing half of what's going on. Still figuring this out myself.
