### ISSUE TITLE
Add documentation on Oncall/Iris integration for messaging

### ISSUE THREAD

**Issue by HITChris** [linkedin/iris#343]
It is not clear to me from the documentation or config comments what config settings are required in order for Oncall to be able to pull from notification_queue and then trigger out a message to the recipient via Iris as the sender. I'm using the annotated config provided via a553c1e from [#334](https://github.com/linkedin/iris/pull/334), which seems to call out the default values related to SMTP, vendor, etc, and likewise I have an entry in the plugin section of Oncall's config defined for iris_messenger. Yet I'm unable to get email messages triggered out of either Iris (via Incident creation) or On-Call (via Reminders/Notifications). Notification_queue continues to hold a ton of rows all marked with NULL for column SENT. Long story short, additional documentation on using Iris as the messaging system would be appreciated.

**Comment by jrgp** [comment]
Can you provide the SMTP settings you are using? Also, do you have iris sender running?

**Comment by HITChris** [comment]
Yep iris-sender is running. What am I missing here?

Iris config -

```
sender:
  debug: False
  process_title: iris-sender
  host: 127.0.0.1
  port: 2321

  workers_per_mode:
    email: 500

  master_sender:
    host: 127.0.0.1
    port: 2321

  api_host: http://localhost:16649

  sender_app: iris
 
  is_master: True

sender_workers: 1000

applications:
 - dummy_app

vendors:
 - type: iris_smtp
   name: email
   smtp_server: '<redacted>'
   smtp_gateway: '<redacted>'
   from: '<redacted>'
```

Oncall config -

```
messengers:
  - type: iris_messenger
    application: iris
    iris_api_key: magic
    api_host: http://localhost:16649
	
notifications:
  default_roles:
    - "primary"
    - "secondary"
    - "manager"
  default_times:
    - 86400
    - 604800
  default_modes:
    - "email"

reminder:
  activated: True
  polling_interval: 360
  default_timezone: 'US/Central'
```

Thanks!
