### ISSUE TITLE
 IRIS ldap not working

### ISSUE THREAD

**Issue by bla-ckbox** [linkedin/iris#716]
Hi,

My goal is to enable LDAP authentication for Iris.

I'm using Iris in a Docker container built from Master branch (Commits on Apr 11, 2022: 6a8a70b1a377636dacdd580e2ba226880be2d79a).

Users are already created in Oncall, LDAP authentication works in Oncall, and user synchronization from oncal to iris is also functional.

I added to the Iris configuration an _Auth_ section very similar to what I already have in oncall but this causes the unavailability of Iris.

```yaml
#LDAP Auth
auth:
  ldap_url: 'ldap://ldap.mycorp.intra'
  ldap_user_suffix: ''
  ldap_bind_user: 'MYCORP\svc-iris'
  ldap_bind_password: 'XXXXXXXXX'
  ldap_base_dn: 'DC=mycorp,DC=intra'
  ldap_search_filter: '(&(objectClass=person)(sAMAccountName=%s))'
```

The web interface returns the error message `Internal Server Error`

Logfile _/home/iris/var/log/uwsgi/error.log_ contains `--- no python application found, check your startup logs for errors ---`

I'm not sure it's a bug maybe I wrote the configuration wrong. Can you help me?
